pub const DOCKED_CONTAINER_HEIGHT: f32 = 64.0;
pub const DOCKED_LEADING_SPACE: f32 = 16.0;
pub const DOCKED_TRAILING_SPACE: f32 = 16.0;
pub const DOCKED_CONTAINER_SHAPE: f32 = super::super::shape::CORNER_NONE;

pub const FLOATING_HORIZONTAL_CONTAINER_HEIGHT: f32 = 64.0;
pub const FLOATING_VERTICAL_CONTAINER_WIDTH: f32 = 64.0;
pub const FLOATING_CONTAINER_LEADING_SPACE: f32 = 8.0;
pub const FLOATING_CONTAINER_TRAILING_SPACE: f32 = 8.0;
pub const FLOATING_CONTAINER_SHAPE: f32 = super::super::shape::CORNER_FULL;
pub const FLOATING_CONTAINER_ELEVATION_LEVEL: u8 = 3;

pub const ACTION_CONTAINER_WIDTH: f32 = 48.0;
pub const ACTION_CONTAINER_HEIGHT: f32 = 48.0;
pub const ACTION_CONTAINER_SHAPE: f32 = super::super::shape::CORNER_FULL;
pub const ACTION_SELECTED_CONTAINER_SHAPE: f32 = super::super::shape::CORNER_MEDIUM;
pub const ACTION_ICON_SIZE: f32 = 24.0;
pub const ACTION_SPACE: f32 = 0.0;
pub const FAB_SPACE: f32 = 8.0;
pub const DISABLED_ICON_OPACITY: f32 = 0.38;
