pub const HOVER_STATE_LAYER_OPACITY: f32 = 0.08;
pub const FOCUS_STATE_LAYER_OPACITY: f32 = 0.10;
pub const PRESSED_STATE_LAYER_OPACITY: f32 = 0.10;
pub const DRAGGED_STATE_LAYER_OPACITY: f32 = 0.16;

pub const DISABLED_CONTAINER_OPACITY: f32 = 0.12;
pub const DISABLED_LABEL_TEXT_OPACITY: f32 = 0.38;
