pub const HOVER_STATE_LAYER_OPACITY: f32 = 0.08;
pub const FOCUS_STATE_LAYER_OPACITY: f32 = 0.10;
pub const PRESSED_STATE_LAYER_OPACITY: f32 = 0.10;
pub const DRAGGED_STATE_LAYER_OPACITY: f32 = 0.16;
pub const STATE_LAYER_TRANSITION_DURATION_MS: u16 = 15;

pub const DISABLED_CONTAINER_OPACITY: f32 = 0.12;
pub const DISABLED_LABEL_TEXT_OPACITY: f32 = 0.38;

pub const RIPPLE_BOUNDED_EXTRA_RADIUS: f32 = 10.0;
pub const RIPPLE_START_RADIUS_FACTOR: f32 = 0.3;
pub const RIPPLE_RADIUS_DURATION_MS: u16 = 225;
pub const RIPPLE_ORIGIN_DURATION_MS: u16 = 225;
pub const RIPPLE_FADE_IN_DURATION_MS: u16 = 75;
pub const RIPPLE_FADE_OUT_DURATION_MS: u16 = 150;
pub const RIPPLE_OPACITY_HOLD_DURATION_MS: u16 = RIPPLE_FADE_IN_DURATION_MS + 150;
pub const RIPPLE_MAX_RIPPLES: usize = 10;

pub const RIPPLE_PATTERN_ENTER_DURATION_MS: u16 = 450;
pub const RIPPLE_PATTERN_EXIT_DURATION_MS: u16 = 375;
pub const RIPPLE_PATTERN_BACKGROUND_OPACITY_DURATION_MS: u16 = 80;
pub const RIPPLE_PATTERN_NOISE_ANIMATION_DURATION_MS: u16 = 7000;
pub const RIPPLE_PATTERN_RADIUS_SCALE: f32 = 2.3;
pub const RIPPLE_PATTERN_FADE_IN_END: f32 = 0.13;
pub const RIPPLE_PATTERN_FADE_OUT_START: f32 = 0.4;
pub const RIPPLE_PATTERN_FADE_OUT_NOISE_END: f32 = 0.5;
pub const RIPPLE_PATTERN_SOFT_CIRCLE_BLUR: f32 = 1.0;
pub const RIPPLE_PATTERN_SOFT_RING_THICKNESS: f32 = 0.05;
pub const RIPPLE_PATTERN_NOISE_DENSITY_SCALE: f32 = 2.1;
pub const RIPPLE_PATTERN_DEFAULT_EFFECT_ALPHA: f32 = 0x8d as f32 / 255.0;
